// Objective-C API for talking to github.com/mileschet/nym-mobile-client Go package.
//   gobind -lang=objc github.com/mileschet/nym-mobile-client
//
// File is generated by gobind. Do not edit.

#ifndef __Nymmobile_H__
#define __Nymmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * GenerateKeyPair
 */
FOUNDATION_EXPORT void NymmobileGenerateKeyPair(NSString* _Nullable id_, NSString* _Nullable homeDirectory, NSString* _Nullable defaultProviderID);

/**
 * GetLocalIP returns the non loopback local IP of the host
from https://stackoverflow.com/questions/23558425/how-do-i-get-the-local-ip-address-in-go
 */
FOUNDATION_EXPORT NSString* _Nonnull NymmobileGetLocalIP(void);

/**
 * Shutdown the mix client
 */
FOUNDATION_EXPORT void NymmobileShutdown(NSString* _Nullable id_, NSString* _Nullable homeDirectory);

/**
 * StartWebsocket starts a websocket client server
 */
FOUNDATION_EXPORT NSString* _Nonnull NymmobileStartWebsocket(NSString* _Nullable id_, NSString* _Nullable homeDirectory);

#endif
