
// Objective-C API for talking to the following Go packages
//
//	github.com/mileschet/nym-mobile-client
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Nymmobile_FRAMEWORK_H__
#define __Nymmobile_FRAMEWORK_H__

#include "Nymmobile.objc.h"
#include "Universe.objc.h"

#endif
